cda-tum/dd_package

- CMakeLists.txt
- LICENSE
- README.md
- include/dd/ComplexValue.hpp
- include/dd/Export.hpp
- include/dd/Package.hpp
- test/bench_package.cpp
- test/test_complex.cpp
- test/test_package.cpp
This PR adds the essential functionality to the JKQ DD Package to support hybrid Schrödinger-Feynman simulation.
The main change is that decision diagrams might now "start" (from the bottom) with a different qubit than 0, which is needed for splitting the circuit horizontally.
Additionally, this PR adds functionality that allows to efficiently export a complete set of amplitudes from a state vector DD and to transfer an existing DD to another package instance.
✨ state generation, matrix generation, and multiplication receive an additional parameter `start` (default 0) that indicates the bottom-most qubit the DD is built from
💥 removed the `makeGateDD` constructor taking two `Qubit` arguments for control and target, as it is ambiguous with the new `start` parameter
✨ method for deleting a …
> Hybrid Schrödinger-Feynman Simulation Preparation

- include/dd/Package.hpp
This PR modifies some functions so that Python bindings in the simulator can be used more easily.
:boom: change amplitude addition/export to use `std::complex` instead of `ComplexValue`
:arrow_up: googletest
> Modifications for Hybrid Simulator Bindings

- include/dd/ComplexValue.hpp
- include/dd/Definitions.hpp
- include/dd/Package.hpp
- test/test_package.cpp
Up until now, our proprietary `ComplexValue` class was used for exporting vectors and matrices. This necessitates writing routines for dumping JSON representations thereof. This PR changes the respective typedefs to use the C++-native `std::complex` class.
> Use `std::complex` for vector and matrix output

- include/dd/GateMatrixDefinitions.hpp
Due to unknown reasons the definition of the RZ gate matrix was wrong. 
This hasn't come up until now since OpenQASM's `qelib1.inc` translates `rz(...)` to `p(...)`, which is implemented correctly.
It only became apparent now due to IBM switching to the new `[rz, sx, cx]` gate set.
> Fix RZ gate matrix definition

- .github/workflows/ci.yml
- .gitmodules
- include/dd/ComplexTable.hpp
- include/dd/Definitions.hpp
- include/dd/Package.hpp
- test/test_complex.cpp
- test/test_package.cpp
This PR brings some minor improvements for functions related to dynamic circuits. In particular it introduces sparse vectors for the representation of probability vectors. This is much more efficient in many cases than trying to allocate a full 2^n dimensional array. In addition, it introduces a `isCloseToIdentity` function that allows to check whether a given matrix is equal to the identity up to a given tolerance.
Furthermore, it fixes a few bugs related to the width of certain variables that prevented some functions to work for more than 32 qubits.
Last but not least, it updates the external dependencies to their latest version.
> Improvements for dynamic circuits

- CMakeLists.txt
Added a test in the CMakeLists.txt before adding the -march=native flag
The latest clang (clang-1300.0.29.30) on Apple M1 does not support it (yet?)
> Test for compiler flag -march=native

- include/dd/Package.hpp
This tiny PR fixes a missing include introduced in the latest PR.
> 🐛 fix missing include

- .github/dependabot.yml
We do not actively depend on updates of the `googletest` and `benchmark` submodules. As such, they create a lot of noise every week via dependabot updates for little to no benefit. This propagates through all of our repositories via the QFR and is amplified by both repositories "living at head".
This PR reduces the dependabot frequency for submodules to monthly (from weekly) in order to reduce the number of PRs created throughout our tools each week.
> 🔧 Reduce dependabot frequency for submodules

- .clang-tidy
- .github/workflows/ci.yml
- .github/workflows/cpp-linter.yml
- CMakeLists.txt
- include/dd/Complex.hpp
- include/dd/ComplexCache.hpp
- include/dd/ComplexNumbers.hpp
- include/dd/ComplexTable.hpp
- include/dd/ComplexValue.hpp
- include/dd/ComputeTable.hpp
- include/dd/Control.hpp
- include/dd/Definitions.hpp
- include/dd/DensityNoiseTable.hpp
- include/dd/Edge.hpp
- include/dd/Export.hpp
- include/dd/GateMatrixDefinitions.hpp
- include/dd/Node.hpp
- include/dd/Package.hpp
- include/dd/StochasticNoiseOperationTable.hpp
- include/dd/ToffoliTable.hpp
- include/dd/UnaryComputeTable.hpp
- include/dd/UniqueTable.hpp
- test/CMakeLists.txt
- test/bench_package.cpp
- test/main.cpp
- test/test_complex.cpp
- test/test_package.cpp
This PR introduces a new CI job to check for compliance via Clang Tidy.
This includes checking variable and function names, warnings for C-style casts and a few more.
(Recreated from #103)
> Integrate Clang-Tidy Workflow for DD Package

- include/dd/Export.hpp
There is different handling of short and std::uint_fast8_t for ostreams that causes zero bytes in the output.
This in turn caused https://github.com/cda-tum/ddvis/issues/105
> Fixed error in dot output

- include/dd/Export.hpp
This PR fixes a bug occurring under C++20 involving unicode literals and UTF-8 strings. For further context, see https://stackoverflow.com/questions/56833000/c20-with-u8-char8-t-and-stdstring). The workaround is taken from https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1423r2.html.
> 🐛 Fix unicode literals for C++20

- CMakeLists.txt
https://github.com/cda-tum/qmap/pull/203 has shown that one of the recent updates in the core repositories has introduced a new internal compiler error situation. Bisecting the cause for the error lead to https://github.com/cda-tum/dd_package/pull/122, which, at first, was quite surprising.
It turns out that https://github.com/cda-tum/dd_package/pull/122 rather unintentionally fixed a bug in the `enable_lto` macro which led to LTO not being enabled at all.
Thus, the failure in https://github.com/cda-tum/qmap/pull/203 is a consequence of LTO being properly enabled.
After experimenting a little bit and googling around, it turns out that unconditionally adding debug symbols (i.e., `-g`) resolves the underlying error.
> 🐛 Fix for upstream LTO internal compiler error

- include/dd/Package.hpp
- test/test_package.cpp
This PR simplifies the templating of the DD package.
For one, this reduces the redundancies in specifying a configuration and then duplicating all entries in the template list for the Package instance (which can also be a terrible source for errors).
In addition, this also allows to refactor all upstream code using 
```c++
template<class DDPackage = dd::Package<>> func(std::unique_ptr<DDPackage> dd)
```
to
```c++
template<class Config = dd::DDPackageConfig> func(std::unique_ptr<dd::Package<Config>> dd)
```
This allows IDEs to properly pick up the type of `dd` and offer code completion, proper error messages in proper places, and much more.
Corresponding PRs demonstrating the advantage are on their way for the QFR and QCEC.
> 🚸 Better DD package templating

- include/dd/Package.hpp
- test/test_package.cpp
This PR adds a convenience function to the DD package that allows to create states from (dense) state vectors.
It uses the "textbook" recursive decomposition into halves to build up the DD.
In the future, this might be useful to export to Python, to make decision diagrams more accessible.
> ✨ DDs from State Vectors

- include/dd/ComplexNumbers.hpp
- include/dd/Package.hpp
- test/test_package.cpp
This contains the implementation of the function makeDDFromMatrix() which allows an arbitrary matrix to be converted to a matrix decision diagram.
A private function makeDDFromMatrix() is usedrecursively to cut a matrix into fourths similar to makeStateFromVector().
> DDs from matrix

- include/dd/GateMatrixDefinitions.hpp
- include/dd/Package.hpp
- test/test_package.cpp
This PR implements a new routine in the DD package that allows to directly construct the decision diagram for any two-qubit operation from a 4x4 matrix description. 
An initial benefit of this is that DDs for gates such as the SWAP and iSWAP can now be constructed natively without puzzling them together from individual gate descriptions. This should improve runtime as well as Unique/Compute Table pollution.
Furthermore, this PR significantly extends the number of supported two-qubit gates, which should now match Qiskit's standard gates. More precisely, it adds the following gates:
- `DCX` (double CNOT)
- `ECR` (cross-resonance)
- `RZZ(\theta)` (ZZ rotation gate)
- `RXX(\theta)` (XX rotation gate)
- `RYY(\theta)` (YY rotation gate)
- `RZX(\theta)` (ZX rotation gate)
- `XXMinusYY(\theta, …
> ✨ Two-Qubit Gate Extensions

- include/dd/Definitions.hpp
- include/dd/Export.hpp
- include/dd/Package.hpp
- include/dd/StochasticNoiseOperationTable.hpp
- test/test_package.cpp
Fixes #117.
The error there is the use of `std::int_fast8_t` for `dd::Qubit`. On most systems, this actually results in an `8`bit integer type, but the standard only guarantees that this is the fastest type for handling 8bit integers on the machine, i.e., it might be wider. When it's 32bits, `MAX_POSSIBLE_QUBITS=2147483648`. Allocating a package of that size will fail on almost all systems imaginable.
This PR fixes the underlying issue by relying on fixed-width integer types. Although these are not mandated by the standard, every major platform we aim to support, provides these types. And it at least allows the program to fail at compile time on exotic systems instead of leading to a cryptic runtime error as in #117. 
We can always adapt once an exotic system pops up that we still might …
> 🩹 Use fixed-width integer types

- include/dd/Package.hpp
This pull request fixes the inner product not considering the top edge weight properly. This was not noticed until now since the inner product has been used with the fidelity which squares the result, however this change was necessary for the expectation value to work.
Included are also:
1. Renaming of variable ip to expValue in the expectationValue function
2. Swap conjugation from second input of innerProduct to first input to be more mathematically consistent (i.e. innerProduct(x, y) = <x|y>
3. Some small comments as well as docstrings for the public and private innerProduct functions.
> fixed inner product not conjugating top edge weight

- include/dd/Package.hpp
- test/test_package.cpp
This pull request fixes the conjugated variable xCopy not being input into the publc inner product function. The inner product was modified in a previous commit to consider the top level node and somehow this detail was missed in the final pull request.
A test case was also created to check that the expectation value (and therefore the inner product) works properly. This test case was based on experimental results of the Ising model evolving a state up to T=1 (i.e. a 2-qubit circuit with an Rxx(-2) rotation).
> fixed inner product bug and created test case

- CMakeLists.txt
- cmake/PackageAddTest.cmake
- test/CMakeLists.txt
This small PR makes sure that CMake are only added if they do not exist already. This avoids problems when multiple versions of the DDPackage are part of the same repository
> 🚸 only add CMake targets if they do not exist

- README.md
All code has been migrated to the [MQT Core](https://github.com/cda-tum/mqt-core) library.
Any development is expected to continue there.
The main reason for this change was the increased effort that was necessary to maintain a hierarchy of packages.
It became quite inconvenient to not have the notion of a quantum circuit or a dedicated parser available in the package as well as having to duplicate structs because of the hierarchy (e.g. `Control`).
> 📣 [NOTICE] This repo is being deprecated
